//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2Stats.Downloader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/PlayerStats.aspx?player=")]
        public string OverviewBaseURL {
            get {
                return ((string)(this["OverviewBaseURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/PlayerGameList.aspx?player=")]
        public string GameListBaseURL {
            get {
                return ((string)(this["GameListBaseURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/PlayerGameList.aspx?player={0}&page={1}")]
        public string GameListPageURL {
            get {
                return ((string)(this["GameListPageURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a id=\"RecentGames_ctl[0-9]*_GameLink\" class=\"span\" href=\"\\/Stats\\/GameStats.aspx" +
            "\\?gameID=[0-9]*&amp;player=")]
        public string FindValidGamesRegex {
            get {
                return ((string)(this["FindValidGamesRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/GameStats.aspx?gameID=")]
        public string MainStatsPageURL {
            get {
                return ((string)(this["MainStatsPageURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/GameStats.aspx?panel=kills&gameid=")]
        public string KillsStatsPageURL {
            get {
                return ((string)(this["KillsStatsPageURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/GameStats.aspx?panel=vs&gameid=")]
        public string PvPStatsPageURL {
            get {
                return ((string)(this["PvPStatsPageURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/GameStats.aspx?panel=hits&gameid=")]
        public string HitsStatsPageURL {
            get {
                return ((string)(this["HitsStatsPageURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/GameStats.aspx?panel=medals&gameid=")]
        public string MedalsStatsPageURL {
            get {
                return ((string)(this["MedalsStatsPageURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("We’re sorry, this game has been partially purged.")]
        public string GamePurgedMessage {
            get {
                return ((string)(this["GamePurgedMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"C:\\Documents and Settings\\Matt\\My D" +
            "ocuments\\CSharp\\h2stats.mdb\"")]
        public string h2statsConnectionString {
            get {
                return ((string)(this["h2statsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/GameStats.aspx?panel={0}&gameid={1}")]
        public string StatsPageUrls {
            get {
                return ((string)(this["StatsPageUrls"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<h4 class=\"Header\">(.*?)<\\/h4>")]
        public string FindMapRegex {
            get {
                return ((string)(this["FindMapRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span class=\"HeaderSub\">(.*?)<\\/span>")]
        public string FindMatchTypeRegex {
            get {
                return ((string)(this["FindMatchTypeRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span class=\"HeaderInfo\">(.*?)<\\/span>[<BR>|<br>]")]
        public string FindPlaylistDateLength {
            get {
                return ((string)(this["FindPlaylistDateLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("07:00:00")]
        public global::System.TimeSpan BungieTimeOffset {
            get {
                return ((global::System.TimeSpan)(this["BungieTimeOffset"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("13")]
        public int GameLengthBeginningIndex {
            get {
                return ((int)(this["GameLengthBeginningIndex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PlayerStat1Hdr\" align=\"center\"><img .*?=\"/images/spacer.gif\" width=\"100\" height=\"" +
            "1\" border=\"0\" alt=\"\"><br><h4>(.*?)<\\/h4><\\/td>")]
        public string FindStat1NameRegex {
            get {
                return ((string)(this["FindStat1NameRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td><img SRC=\"/images/spacer.gif\" width=\"190\" height=\"1\" border=\"0\" alt=\"\"><br><h" +
            "4>Team</h4></td>")]
        public string TeamScoreHeaderCode {
            get {
                return ((string)(this["TeamScoreHeaderCode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PlayerStat2Hdr\" align=\"center\"><img .*?=\"/images/spacer.gif\" width=\"90\" height=\"1" +
            "\" border=\"0\" alt=\"\"><br><h4>(.*?)<\\/h4><\\/td>")]
        public string FindStat2NameRegex {
            get {
                return ((string)(this["FindStat2NameRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a id=\"PlayerListCtrl_pldStats_rpPlayerList_ctl.*?_GamertagLink\" class=\"ContentTe" +
            "xt\".*?>(.*?)<\\/a><")]
        public string FindGamertagsRegex {
            get {
                return ((string)(this["FindGamertagsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldStats_rpPlayerList_ctl{0:00}_tdStat1\" align=\"center\" bg" +
            "color=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)<\\/span><\\/td>")]
        public string FindStat1ValueRegex {
            get {
                return ((string)(this["FindStat1ValueRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MM/d/yyyy h:m tt")]
        public string DateTimeFormat {
            get {
                return ((string)(this["DateTimeFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hh:mm:ss")]
        public string TimeFormat {
            get {
                return ((string)(this["TimeFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldStats_rpPlayerList_ctl{0:00}_tdScore\" bgcolor=\"[abcdef0" +
            "-9]*\">\r\n\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"55\" height=" +
            "\"20px\">\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td align=\"center\"><span class=\"ContentText\">(.*?)</span" +
            "></td>")]
        public string FindScoreValueRegex {
            get {
                return ((string)(this["FindScoreValueRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldStats_rpPlayerList_ctl{0:00}_tdStat2\" align=\"center\" bg" +
            "color=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindStat2ValueRegex {
            get {
                return ((string)(this["FindStat2ValueRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldStats_rpPlayerList_ctl{0:00}_tdStat1\" align=\"center\" bg" +
            "color=\"(.*?)\">")]
        public string FindColorRegex {
            get {
                return ((string)(this["FindColorRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldKills_rpPlayerList_ctl{0:00}_tdKills\" align=\"center\" bg" +
            "color=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindKillsRegex {
            get {
                return ((string)(this["FindKillsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldKills_rpPlayerList_ctl{0:00}_tdAssists\" align=\"center\" " +
            "bgcolor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindAssistsRegex {
            get {
                return ((string)(this["FindAssistsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldKills_rpPlayerList_ctl{0:00}_tdDeaths\" align=\"center\" b" +
            "gcolor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindDeathsRegex {
            get {
                return ((string)(this["FindDeathsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldKills_rpPlayerList_ctl{0:00}_tdSuicides\" bgcolor=\"[abcd" +
            "ef0-9]*\">\r\n\t\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" width=\"65\" heig" +
            "ht=\"20px\">\r\n\t\t\t\t<tr>\r\n\t\t\t\t\t<td align=\"center\"><span class=\"ContentText\">(.*?)</s" +
            "pan></td>")]
        public string FindSuicidesRegex {
            get {
                return ((string)(this["FindSuicidesRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldVs_rpPlayerList_ctl{0:00}_tdReaper\" align=\"center\" bgco" +
            "lor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindMostKilledByRegex {
            get {
                return ((string)(this["FindMostKilledByRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldVs_rpPlayerList_ctl{0:00}_tdFodder\" align=\"center\" bgco" +
            "lor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindMostKilledRegex {
            get {
                return ((string)(this["FindMostKilledRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldHits_rpPlayerList_ctl{0:00}_tdHits\" align=\"center\" bgco" +
            "lor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindShotsHitRegex {
            get {
                return ((string)(this["FindShotsHitRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldHits_rpPlayerList_ctl{0:00}_tdFired\" align=\"center\" bgc" +
            "olor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindShotsFiredRegex {
            get {
                return ((string)(this["FindShotsFiredRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldHits_rpPlayerList_ctl{0:00}_tdAccuracy\" align=\"center\" " +
            "bgcolor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindAccuracyRegex {
            get {
                return ((string)(this["FindAccuracyRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<td id=""PlayerListCtrl_pldHits_rpPlayerList_ctl{0:00}_tdHeadShots"" align=""center"" bgcolor=""[abcdef0-9]*"">
				<table cellpadding=""0"" cellspacing=""0"" border=""0"" width=""55"" height=""20px"">
				<tr>
					<td align=""center""><span class=""ContentText"">(.*?)</span></td>")]
        public string FindHeadshotsRegex {
            get {
                return ((string)(this["FindHeadshotsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_rpPlayerList_ctl{0:00}_tdMedalAmt\" align=\"center\" bgcolor=" +
            "\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)<\\/span><\\/td>")]
        public string FindTotalMedalsRegex {
            get {
                return ((string)(this["FindTotalMedalsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td valign=\"center\" width=\"15\" align=\"right\"><span class=\"ContentText\">(.*?)<\\/sp" +
            "an>")]
        public string FindAllMedalValuesRegex {
            get {
                return ((string)(this["FindAllMedalValuesRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td><a href=\"#\" title=\"(.*?) -")]
        public string FindAllMedalNamesRegex {
            get {
                return ((string)(this["FindAllMedalNamesRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldMedals_rpPlayerList_ctl{0:00}_tdMedalAmt\" align=\"center" +
            "\" bgcolor=\"[abcdef0-9]*\"><span class=\"ContentText\">(.*?)</span></td>")]
        public string FindMedalCountRegex {
            get {
                return ((string)(this["FindMedalCountRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<img id=\"StatsHeadControl_EmblemCtrl_imgEmblem\" src=\"(.*?)\"")]
        public string FindIconUrlRegex {
            get {
                return ((string)(this["FindIconUrlRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span id=\"dlHopperRanks_ctl[0-9]*_HopperName\">(.*?)<\\/span>")]
        public string FindAllPlaylistNamesRegex {
            get {
                return ((string)(this["FindAllPlaylistNamesRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div class=\"ExpBarText\" style=\"left:20\">([0-9]*?)<\\/div>")]
        public string FindAllPlaylistRanksRegex {
            get {
                return ((string)(this["FindAllPlaylistRanksRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td background=\"/images/Themes/Halo2Stats/LevelBar.gif\"><img src=\"/images/spacer." +
            "gif\" border=\"0\" width=\"([0-9]*?)\"")]
        public string FindAllRankPercentRegex {
            get {
                return ((string)(this["FindAllRankPercentRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td align=\"center\"><span>\r\n\t\t\t\t\t\t\t\t\t([0-9]*?)</span>")]
        public string FindAllGamesAndWinsRegex {
            get {
                return ((string)(this["FindAllGamesAndWinsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td align=\"center\" bgcolor=\"{0}\">.+?<span class=\"ContentText\">(.*?)</span>")]
        public string FindBetrayalsRegex {
            get {
                return ((string)(this["FindBetrayalsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<p><b><font color=\"white\">{0}<\\/font><\\/b><br>\r\n(.*?)<p><\\/p>")]
        public string FindPlaylistInfoRegex {
            get {
                return ((string)(this["FindPlaylistInfoRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<p>Ranked: <b>([A-Z]*?)<\\/b>")]
        public string FindRankedRegex {
            get {
                return ((string)(this["FindRankedRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/page.aspx?section=FAQInfo&subsection=playlists&page=1" +
            "")]
        public string PlaylistInfoUrl {
            get {
                return ((string)(this["PlaylistInfoUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<span><i>(.*?)<\\/i><\\/span>")]
        public string FindPlaylistDescriptionRegex {
            get {
                return ((string)(this["FindPlaylistDescriptionRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<div id=\"PlayerListCtrl_pldVs_rpPlayerList_ctl{0:00}_pnlVsDisplay\" style=\"backgro" +
            "und-color:#154978;display:none;\">(.*?)<td id=\"PlayerListCtrl_pldVs_rpPlayerList_" +
            "ctl")]
        public string FindBetrayalsTableRegex {
            get {
                return ((string)(this["FindBetrayalsTableRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<a href=\"/Stats/ClanStats.aspx?clan=(.*?)\">")]
        public string FindClanRegex {
            get {
                return ((string)(this["FindClanRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<p><b><font color=\"white\">(.*?)<\\/font><\\/b><br>\r\n<div class=\"RuleSmallTop\"></div" +
            ">")]
        public string FindAllCurrentPlaylistsRegex {
            get {
                return ((string)(this["FindAllCurrentPlaylistsRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<td id=\"PlayerListCtrl_pldStats_rpPlayerList_ctl{0:00}_tdRank\" style=\"text-align:" +
            "left\"><span>([0-9]*?)[a-z]*</span></td>")]
        public string FindPlaceRegex {
            get {
                return ((string)(this["FindPlaceRegex"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<table id=""PlayerListCtrl_pldMedals_rpPlayerList_ctl{0:00}_dlPlayerMedals"" cellspacing=""0"" cellpadding=""0"" border=""0"">(.*?)<td align=""right"" width=""7"" valign=""bottom""><img SRC=""/images/Themes/Halo2Stats/CornerLowerRight.gif"" width=""7"" height=""7"" border=""0"" alt=""""></td>")]
        public string FindMedalTableRegex {
            get {
                return ((string)(this["FindMedalTableRegex"]));
            }
        }
    }
}
