//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H2Stats.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\Projects\\h2stats\\h2stats.mdb")]
        public string h2statsConnectionString {
            get {
                return ((string)(this["h2statsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.bungie.net/Stats/PlayerStats.aspx?player=")]
        public string StatsBaseUrl {
            get {
                return ((string)(this["StatsBaseUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point DownloadFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["DownloadFormLocation"]));
            }
            set {
                this["DownloadFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("266, 421")]
        public global::System.Drawing.Size DownloadFormSize {
            get {
                return ((global::System.Drawing.Size)(this["DownloadFormSize"]));
            }
            set {
                this["DownloadFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastViewedGamertag {
            get {
                return ((string)(this["LastViewedGamertag"]));
            }
            set {
                this["LastViewedGamertag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DownloadAll {
            get {
                return ((bool)(this["DownloadAll"]));
            }
            set {
                this["DownloadAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StatNameColumnWidth {
            get {
                return ((int)(this["StatNameColumnWidth"]));
            }
            set {
                this["StatNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StatTotalColumnWidth {
            get {
                return ((int)(this["StatTotalColumnWidth"]));
            }
            set {
                this["StatTotalColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point TotalFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["TotalFormLocation"]));
            }
            set {
                this["TotalFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StatAverageColumnWidth {
            get {
                return ((int)(this["StatAverageColumnWidth"]));
            }
            set {
                this["StatAverageColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StatMinColumnWidth {
            get {
                return ((int)(this["StatMinColumnWidth"]));
            }
            set {
                this["StatMinColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StatMaxColumnWidth {
            get {
                return ((int)(this["StatMaxColumnWidth"]));
            }
            set {
                this["StatMaxColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int StatStdDevColumnWidth {
            get {
                return ((int)(this["StatStdDevColumnWidth"]));
            }
            set {
                this["StatStdDevColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MedalIconColumnWidth {
            get {
                return ((int)(this["MedalIconColumnWidth"]));
            }
            set {
                this["MedalIconColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MedalNameColumnWidth {
            get {
                return ((int)(this["MedalNameColumnWidth"]));
            }
            set {
                this["MedalNameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MedalTotalColumnWidth {
            get {
                return ((int)(this["MedalTotalColumnWidth"]));
            }
            set {
                this["MedalTotalColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MedalAvgColumnWidth {
            get {
                return ((int)(this["MedalAvgColumnWidth"]));
            }
            set {
                this["MedalAvgColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MedalMinColumnWidth {
            get {
                return ((int)(this["MedalMinColumnWidth"]));
            }
            set {
                this["MedalMinColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MedalMaxColumnWidth {
            get {
                return ((int)(this["MedalMaxColumnWidth"]));
            }
            set {
                this["MedalMaxColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MedalStdDevColumnWidth {
            get {
                return ((int)(this["MedalStdDevColumnWidth"]));
            }
            set {
                this["MedalStdDevColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TotalBytesDL {
            get {
                return ((int)(this["TotalBytesDL"]));
            }
            set {
                this["TotalBytesDL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int GamesDL {
            get {
                return ((int)(this["GamesDL"]));
            }
            set {
                this["GamesDL"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://h2.halowiki.net/p/")]
        public string H2WikiBaseUrl {
            get {
                return ((string)(this["H2WikiBaseUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsedGameViewer {
            get {
                return ((string)(this["LastUsedGameViewer"]));
            }
            set {
                this["LastUsedGameViewer"] = value;
            }
        }
    }
}
